const ourProjects = [
  {
    "name": "Snoonu",
    "title": "E-commerce Ecosystem (Marketplace, Restaurants & Cafes)",
    "origin": "Qatar",
    "techStack": ["AWS", "GCP", "Android – Kotlin", "iOS – Swift", "PostgreSQL", ".NET", "Vue.js", "Python", "GitLab", "GitHub", "Secureframe", "SOCRadar"],
    "path": "/projects/snoonu",
    "slug": "snoonu",
    "description": "Contributed to the development of an e-commerce platform, including its market and services for restaurants and cafes. Managed cross-platform integration, implemented scalable cloud infrastructure, and automated deployments through CI/CD pipelines. Ensured system security, compliance, and reliability using tools like Secureframe, SOCRadar, and cloud-native solutions.",
    "link": "https://snoonu.com/",
    "img": "/images/projects/project-01/snoonu.png",
    "category": "Web application",
    "year": '2024'
  },
  {
    "name": "Localised",
    "title": "E-commerce Platform Offering Designer Clothing, Accessories, and Beauty Products",
    "origin": "USA",
    "techStack": ["AWS CloudFormation", "AWS Security Services", "Redis", "Drata", "Avast", "QuickSight", "PostgreSQL", "Aurora MySQL", "Docker", "Node.js"],
    "path": "/projects/localised",
    "slug": "localised",
    "description": "Focused on strengthening security, cloud architecture, and infrastructure for an e-commerce platform offering clothing and accessories. Implemented secure and scalable infrastructure using CloudFormation, managed compliance and security monitoring with Drata and Avast, and supported analytics via QuickSight. Worked across containerized environments with Docker and database systems, including PostgreSQL and Aurora MySQL.",
    "link": "https://www.localised.com/",
    "img": "/images/projects/project-01/localized.png",
    "category": "Web application",
    "year": '2024'
  },
  {
    "name": "Boxo",
    "title": "E-commerce & Analytics Platform (Mini-apps, Esins, Remediance Dashboards)",
    "origin": "Singapore",
    "techStack": ["Kubernetes", "Docker", "Terraform", "Jenkins", "GitHub", "GCP", "AWS", "Celery", "Beat-Flower", "Metabase", "Kong Dashboard", "Redis", "PostgreSQL", "CDN", "Python", "Django", "Node.js", "React", "Next.js"],
    "path": "/projects/boxo",
    "slug": "boxo",
    "description": "Developed and managed Kubernetes clusters on GCP, provisioning services as applications for various internal and external projects. Focused on DevOps/DevSecOps practices including CI/CD setup, container orchestration, infrastructure as code, and secure deployments. Supported multiple mini-apps and dashboards for e-commerce analytics, while ensuring compliance with ISO 27001 and SOC 2 security standards.",
    "link": "https://www.boxo.io/",
    "img": "/images/projects/project-01/boxo.png",
    "category": "Web application",
    "year": '2024'
  },
  {
    "name": "Get Cash Cloud",
    "title": "Banking System for Vendor Transactions",
    "origin": "USA",
    "techStack": ["AWS", "Sprinto", "SonarCloud", "Grafana", "Loki", "Promtail", "Cloudflare", "Bitbucket", "Vue.js", "React", "Next.js", "Node.js"],
    "path": "/projects/cashcloud",
    "slug": "cashcloud",
    "description": "Built and maintained a system to manage company transactions with vendors, aiming to optimize billing and reduce costs. Leveraged monitoring tools like Grafana, Loki, and Promtail for observability, while ensuring code quality and compliance with SonarCloud and Sprinto. Implemented secure, scalable infrastructure using AWS and Cloudflare.",
    "link": "https://www.getcashcloud.com/",
    "img": "/images/projects/project-01/c-c.png",
    "category": "Web application",
    "year": '2023'
  },
  {
    "name": "Stay with lumina",
    "title": "Stay with lumina",
    "origin": "UK",
    "techStack": ["NextJs", "React Js", "AWS", "TypeScript" , "MAterial UI",  "GitHub"],
    "path": "/projects/stay-with-lumina",
    "slug": "stay-with-lumina",
    "description": "Built StayWithLumina, a premium vacation rental platform for luxury getaways and business stays. Developed with Next.js, React, TypeScript, and Material UI, it delivers a fast, elegant, and responsive user experience. Key features include curated listings, flexible check-ins, 24/7 support, and work-friendly spaces. The platform is powered by AWS for scalable performance, with version control managed via GitHub. This project highlights my full-stack development skills in building high-end hospitality solutions.",
    "link": "https://staywithlumina.com/",
    "img": "/images/projects/project-01/swl-1.png",
    "category": "Web application",
    "year": '2025'
  },
  {
    "name": "Outreside",
    "title": "Outreside",
    "origin": "Switzerland",
    "techStack": ["Nodejs" ,"reactjs" ,"typescript" ,"material UI" ,"digital Ocean" ,"GitHub"],
    "path": "/projects/outreside",
    "slug": "outreside",
    "description": "Outreside is a Swiss-based premium outdoor living brand specializing in high-quality products for gardens and terraces. Their curated selection includes outdoor kitchens, grills, pizza ovens, furniture, and garden décor, all designed to enhance outdoor experiences. With a commitment to craftsmanship and a passion for nature, Outreside aims to inspire individuals to embrace the outdoors and create memorable moments in their own spaces.",
    "link": "https://outreside.com/",
    "img": "/images/projects/project-01/otre.png",
    "category": "Web application",
    "year": '2025'
  },
  {
    "name": "Hotel Weekend",
    "title": "Hotel Weekend",
    "origin": "Netherlands",
    "techStack": ["Squarespace" ,"Squarespace Commerce" ,"HSTS" ,"Open Graph" ,"YUI" ,"GitHub", "Modernizr"],
    "path": "/projects/hotel-weekend",
    "slug": "hotel-weekend",
    "description": "Worked on Hotel Weekend, a curated travel platform built with Squarespace and Squarespace Commerce, focusing on design-driven property listings and editorial content. The site leverages Open Graph, Modernizr, and YUI for enhanced UX and compatibility, with SEO and security powered by HSTS. Version control was managed via GitHub.",
    "link": "https://www.hotel-weekend.com/",
    "img": "/images/projects/project-01/hw.png",
    "category": "Web application",
    "year": '2022'
  },
  {
    "name": "Psych Plus",
    "title": "Health Care System (Multi-Branch Hospital Management)",
    "origin": "USA",
    "techStack": ["Azure", "GitHub Actions (CI/CD)", "Terraform", "Kubernetes", ".NET", "React", "SQL Server", "Helm", "Docker", "SonarQube", "Cloud Defender", "Cloudflare"],
    "path": "/projects/psychplus",
    "slug": "psychplus",
    "description": "Managed infrastructure and deployment workflows for a healthcare system supporting multiple hospital branches. Implemented scalable infrastructure using Terraform and Azure, automated deployments with GitHub Actions, and orchestrated containers via Kubernetes and Helm. Ensured system security, reliability, and compliance with tools like Cloud Defender, Cloudflare, and SonarQube.",
    "link": "https://psychplus.com/",
    "img": "/images/projects/project-01/psych.png",
    "category": "Web application",
    "year": '2024'
  },
  {
    "name": "Alert Management System",
    "title": "Alert Management System",
    "origin": "Czech Republic",
    "techStack": ["Moogsoft", "Dynatrace", "Rundeck", "Splunk", "Ariba Ops", "MON", "Jenkins", "Datadog", "SAP Ariba Cloud"],
    "path": "/projects/alert-management",
    "slug": "alert-management",
    "description": "Handled site reliability monitoring and alert management for critical infrastructure. Monitored server clusters, managed incident responses, and ensured minimal downtime by proactively resolving system outages using observability tools like Dynatrace, Splunk, and Moogsoft. Maintained automated workflows via Jenkins and Rundeck for operational efficiency.",
    "link": "",
    "img": "/images/projects/project-01/placeholder.png",
    "category": "Cloud application",
    "year": '2024'
  },
  {
    "name": "Enterprise System",
    "title": "Enterprise System (ERP Platform)",
    "origin": "Czech Republic",
    "techStack": ["Delinea Secret Server", "GitHub", "Terraform", "Ansible Tower", "Jenkins (CI/CD)", "Jump Host", "GCP", "BigFive", "Global VPN", "ClamAV", "Dynatrace"],
    "path": "/projects/erp-platform",
    "slug": "erp-platform",
    "description": "Managed enterprise infrastructure focusing on automated provisioning using Terraform integrated with Jenkins pipelines. Resolved server vulnerabilities through Ansible playbooks and handled application deployments via Ansible Tower. Ensured secure system operations using jump hosts, secret management, VPN, and antivirus solutions, and monitored system health and performance with Dynatrace.",
    "link": "",
    "img": "/images/projects/project-01/placeholder.png",
    "category": "Cloud application",
    "year": '2024'
  },
  {
    "name": "Building Supplies",
    "title": "Building Supplies & IT Innovator",
    "origin": "UK",
    "techStack": ["AWS", "Bitbucket", "Bitbucket Pipelines", "Vanta", "Cloudflare", "Grafana", "Prometheus", "Sentry", "Laravel Vapor", "GitHub", "GitHub Actions", "PHP", "Aurora MySQL", "DynamoDB", "Redis"],
    "path": "/projects/building-supplies-it",
    "slug": "building-supplies-it",
    "description": "Led DevOps initiatives across both business units—construction material supply and IT innovation. Managed cloud infrastructure on AWS, focusing on cost optimization, billing analysis, and system security through Vanta. Implemented CI/CD workflows using Bitbucket Pipelines and GitHub Actions. Ensured application reliability and performance monitoring with Grafana, Prometheus, and Sentry. Supported scalable application deployments with Laravel Vapor and maintained secure, high-performance databases using Aurora MySQL, DynamoDB, and Redis.",
    "link": "",
    "img": "/images/projects/project-01/placeholder.png",
    "category": "Cloud application",
    "year": '2024'
  },
]

export { ourProjects };
